/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": "@request.auth.id != ''",
    "deleteRule": "@request.auth.id = added_by || @request.auth.role = 'admin'",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1579384326",
        "max": 0,
        "min": 0,
        "name": "name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1914026624",
        "max": 0,
        "min": 0,
        "name": "org",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text2303156493",
        "max": 0,
        "min": 0,
        "name": "designation",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text760939060",
        "max": 0,
        "min": 0,
        "name": "city",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1400097126",
        "max": 0,
        "min": 0,
        "name": "country",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "exceptDomains": null,
        "help": "",
        "hidden": false,
        "id": "email3885137012",
        "name": "email",
        "onlyDomains": null,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "email"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1014178784",
        "max": 0,
        "min": 0,
        "name": "mobile",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "exceptDomains": null,
        "help": "",
        "hidden": false,
        "id": "email4213745938",
        "name": "secondary_email",
        "onlyDomains": null,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "email"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text2562612568",
        "max": 0,
        "min": 0,
        "name": "secondary_mobile",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text2197739809",
        "max": 0,
        "min": 0,
        "name": "how_you_know",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "select1077078561",
        "maxSelect": 10,
        "name": "fu_roles",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "speaker",
          "sponsor",
          "meetup_host",
          "foss_club_ambassador_student",
          "foss_club_ambassador_staff",
          "organising_volunteer",
          "gov_board_expert",
          "mentor",
          "project_maintainer",
          "general"
        ]
      },
      {
        "help": "",
        "hidden": false,
        "id": "select2448836153",
        "maxSelect": 15,
        "name": "topics",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "technologist",
          "hardware",
          "av_enthusiast",
          "public_policy",
          "ai_ml",
          "government",
          "open_source",
          "education",
          "security",
          "devops",
          "design",
          "community",
          "research",
          "legal",
          "finance"
        ]
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "help": "",
        "hidden": false,
        "id": "relation1771793327",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "added_by",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      }
    ],
    "id": "pbc_1930317162",
    "indexes": [],
    "listRule": "@request.auth.id != ''",
    "name": "contacts",
    "system": false,
    "type": "base",
    "updateRule": "@request.auth.id = added_by || @request.auth.role = 'admin'",
    "viewRule": "@request.auth.id != ''"
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_1930317162");

  return app.delete(collection);
})
